version: 2
updates:
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    groups:
      web-runtime:
        dependency-type: production
        update-types: [minor, patch]
      web-development:
        dependency-type: development
        update-types: [minor, patch]
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /docs
    schedule:
      interval: weekly
    groups:
      docs-dependencies:
        patterns: ["*"]
        update-types: [minor, patch]
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: node
        update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /docs
    schedule:
      interval: weekly
    ignore:
      - dependency-name: node
        update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 5
