import type { ThemeConfig } from "antd";
import { theme as antdTheme } from "antd";

const neutral = {
    light: {
        primary: "#171717",
        primaryHover: "#000000",
        primaryText: "#ffffff",
        menuBg: "#f5f5f5",
        menuText: "#171717",
        selectActiveBg: "#f4f5f7",
        selectSelectedBg: "transparent",
        selectText: "#171717",
        selectBorder: "#c9ced5",
        selectOutline: "rgba(32, 36, 42, 0.08)",
        selectShadow: "0 8px 24px rgba(15, 23, 42, 0.08), 0 2px 6px rgba(15, 23, 42, 0.04)",
        tableSelectedBg: "rgba(17, 17, 17, 0.05)",
        tableSelectedHoverBg: "rgba(17, 17, 17, 0.08)",
        layoutBg: "#fafbfc",
        containerBg: "#ffffff",
        border: "#e5e8ec",
        text: "#20242a",
        textSecondary: "#697381",
    },
    dark: {
        primary: "#fafafa",
        primaryHover: "#ffffff",
        primaryText: "#171717",
        menuBg: "#262626",
        menuText: "#fafafa",
        selectActiveBg: "#262b31",
        selectSelectedBg: "transparent",
        selectText: "#fafafa",
        selectBorder: "#464c55",
        selectOutline: "rgba(255, 255, 255, 0.08)",
        selectShadow: "0 12px 28px rgba(0, 0, 0, 0.28), 0 2px 8px rgba(0, 0, 0, 0.18)",
        tableSelectedBg: "rgba(255, 255, 255, 0.08)",
        tableSelectedHoverBg: "rgba(255, 255, 255, 0.12)",
        layoutBg: "#111316",
        containerBg: "#181b20",
        border: "#2b3037",
        text: "#f3f5f7",
        textSecondary: "#9aa3af",
    },
};

export function getAntThemeConfig(dark: boolean): ThemeConfig {
    const color = dark ? neutral.dark : neutral.light;

    return {
        algorithm: dark ? antdTheme.darkAlgorithm : antdTheme.defaultAlgorithm,
        cssVar: { key: dark ? "vozeb-pro-dark" : "vozeb-pro-light" },
        token: {
            colorPrimary: color.primary,
            colorInfo: color.primary,
            colorLink: color.primary,
            colorLinkHover: color.primaryHover,
            colorLinkActive: color.primary,
            colorTextLightSolid: color.primaryText,
            colorBgLayout: color.layoutBg,
            colorBgContainer: color.containerBg,
            colorBorder: color.border,
            colorText: color.text,
            colorTextSecondary: color.textSecondary,
            borderRadius: 8,
        },
        components: {
            Button: {
                primaryShadow: "none",
            },
            Menu: {
                itemActiveBg: color.menuBg,
                itemHoverBg: color.menuBg,
                itemSelectedBg: color.menuBg,
                itemSelectedColor: color.menuText,
                darkItemHoverBg: neutral.dark.menuBg,
                darkItemSelectedBg: neutral.dark.menuBg,
                darkItemSelectedColor: neutral.dark.menuText,
            },
            Select: {
                activeBorderColor: color.selectBorder,
                activeOutlineColor: color.selectOutline,
                borderRadiusLG: 8,
                borderRadiusSM: 6,
                boxShadowSecondary: color.selectShadow,
                controlItemBgActiveHover: color.selectSelectedBg,
                hoverBorderColor: color.selectBorder,
                optionActiveBg: color.selectActiveBg,
                optionHeight: 32,
                optionPadding: "5px 10px",
                optionSelectedBg: color.selectSelectedBg,
                optionSelectedColor: color.selectText,
                optionSelectedFontWeight: 400,
            },
            Cascader: {
                borderRadiusLG: 8,
                borderRadiusSM: 6,
                boxShadowSecondary: color.selectShadow,
                controlItemBgHover: color.selectActiveBg,
                optionPadding: "5px 10px",
                optionSelectedBg: color.selectSelectedBg,
                optionSelectedColor: color.selectText,
                optionSelectedFontWeight: 400,
            },
            TreeSelect: {
                borderRadiusLG: 8,
                borderRadiusSM: 6,
                boxShadowSecondary: color.selectShadow,
                nodeHoverBg: color.selectActiveBg,
                nodeHoverColor: color.selectText,
                nodeSelectedBg: color.selectSelectedBg,
                nodeSelectedColor: color.selectText,
            },
            Table: {
                rowSelectedBg: color.tableSelectedBg,
                rowSelectedHoverBg: color.tableSelectedHoverBg,
            },
        },
    };
}
